### PR TITLE
Replace use of binaries for getting node information

### LINKED ISSUE #10: Eliminate use of binaries to get node info
Hey, so I was trying to understand how `heiko` is getting node information like CPU and RAM usage and things like that.

I noticed that in a lot of places it's making use of binaries such as `lscpu` and free. That's actually a really convenient way to do it, but I recently found out that in quite a few cases, binaries like `lscpu` aren't installed by default. So that might cause an issue. Another improvement that `heiko` might be able to achieve is, since it's going to be checking for these details multiple times, you'll have to load the binary I to memory atleast once. Instead what you could do is, you could maybe just read the info directly from the source itself that binaries like `lscpu` and free use. 

So for example, for `lscpu`, the info you need can be gotten from `/proc/cpuinfo` and
`/sys/devices/system/cpu*/cpufreq/cpuinfo_max_freq`

For `free` you can get the info from `/proc/meminfo`

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
* Replaced the use of `lscpu` and `free` with reading from files of the `procfs` and `sysfs` subsystems
* Tidied up the docker-networks.py file
* Made compiled regex objects in load.py private to class `NodeDetails` and deleted debug print statements
* Ran code through `black`

TODO:
- [x] Need to figure out how to replace `uptime` binary.

Fix #10

### CODE REVIEW

**Comment by Samyak2** [comment]
This looks great!

Just a small thing. Since current CPU freq and max freq are in different, independent files and their parsing is also independent maybe they could be split into two different functions? This will also prevent the `len//2` trick which seemed a bit confusing at the first look and requires too much explanation for a trivial thing. What do you think?

Also, if you found any of the API weird or confusing, feel free to let us know lol. One thing I could think of was that the `get...` and `parse...` functions are public but it does not make sense to call them separately. The only function currently being used publicly is `getDetails`.

**Comment by MadhavJivrajani** [comment]
That makes sense, I think if we need only max cpu freq then we won't need to read the other set of files and the whole `//2` trick won't be required then, will wait for confirmation on #10 

As per the API, I could make those functions private except the `getDetails`. I'll raise an issue or ping on slack if there's anything else I can think of :smile:

**Comment by MadhavJivrajani** [comment]
@Samyak2 @psiayn any blockers on this?

**Comment by Samyak2** [comment]
Hi,

Sorry, I was going to test it but lost track. I'll test it and approve/merge by tonight.

**Comment by Samyak2** [comment]
Update: I tried testing but ran into a few issues with termux.

The `cat` command exited with SIGABRT everytime:
```
04/01/2021 07:15:41 PM INFO: [conn=0] Auth for user u0_a324 succeeded
04/01/2021 07:15:41 PM INFO: [conn=0, chan=0] Requesting new SSH session
04/01/2021 07:15:41 PM INFO: [conn=0, chan=0]   Command: cat "/proc/meminfo"
04/01/2021 07:15:41 PM INFO: [conn=0, chan=0] Received exit signal ABRT
04/01/2021 07:15:41 PM INFO: [conn=0, chan=0] Received channel close
```

Though it ran without errors in an interactive shell through SSH. I wasn't able to reproduce it until I tried running the command in an non-interactive manner like `ssh -p 8022 user@192.168.0.0 cat /proc/meminfo` (user and IP changed):

```
❯ ssh -p 8022 user@192.168.0.0 cat /proc/meminfo
user@192.168.0.0's password: 
fdsan: attempted to close file descriptor 10, expected to be unowned, actually owned by FILE* 0x7a2ce9ed18
```

Looks like an issue with Termux on Android 11 [1] [2].

I'll try with a different device tomorrow.

[1] https://github.com/termux/termux-packages/issues/5790
[2] Interesting addition to Android 11: https://developer.android.com/about/versions/11/behavior-changes-all#fdsan

**Pull request merged**
