### PR TITLE
Start container in non-root user

### LINKED ISSUE #2: Make the docker-networks.py script run as user instead of root.
As of now, the scripts spawns containers that are root by default. On the other hand, heiko's target devices don't have access to any level of elevated permissions. It would be nice to make it run as user to make simulating and perhaps testing a lot more realistic?

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
Fix #2

### CODE REVIEW

**Comment by Samyak2** [comment]
A little late now xD, but wouldn't this run `useradd` everytime the container is started or `exec`'d into?

**Comment by MadhavJivrajani** [comment]
Yeah you're right, although since the script removes containers, it shouldn't be an issue as such, although yeah it feels super hacky. Thanks for pointing it out, I hadn't realised it earlier.

I'll try looking into this.

**Comment by MadhavJivrajani** [comment]
Is this better?

```Dockerfile
FROM debian:stable-slim

# install dependencies
RUN apt update && apt upgrade -y
RUN apt install openssh-server vim sudo -y

# set password for root user
RUN echo 'root:yabe' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

RUN useradd -rm -d /home/test -s /bin/bash -u 1000 -G sudo test

RUN echo 'test:yabe' | chpasswd

USER test
WORKDIR /home/test

# start ssh service
ENTRYPOINT  echo yabe | sudo -S service ssh restart && bash
```
I'm not entirely sure about how you want to test it, but is it okay if the user is in the group of sudoers?

**Comment by Samyak2** [comment]
That looks much better!

The user being in sudoers shouldn't be a big issue. As long as we don't use commands with `sudo`, right?

**Comment by MadhavJivrajani** [comment]
Yeah
@psiayn what do you think?

**Comment by psiayn** [comment]
Oh yeah, makes sense!

**Pull request merged**
